### PR TITLE
PositionVelocityTimeEventargs : Flags and Flags2

### PR DESCRIPTION
**Pull request by valeriob**

### CODE REVIEW

**Comment by jefffhaynes** [comment]
Please rename your Eventargs files to have a capital A.  I have to force rename every time because the case changes aren't picked up.  Thanks

**Comment by valeriob** [comment]
Ok, tnx!

**Comment by valeriob** [comment]
Hi,
thanks for finding the time to merge my pull requests 😄 
I found version 0.2.1 on nuget, it contains #4 but not the code of this pull request, could you check it out or make a new release pls ?
Thanks

**Comment by jefffhaynes** [comment]
Ah, sorry about that, I built the wrong branch.  Try 2.2, just pushed.

**Pull request merged**
