### PR TITLE
Read packet RXM_RAWX

### PR DESCRIPTION
**Pull request by valeriob**

### CODE REVIEW

**Comment by jefffhaynes** [comment]
Can you please change the naming to match what’s in the library (and C# naming standard)?  For example, RXM_RAWX should probably be RawDataProductVariant or something similar. 

Thanks

**Comment by jefffhaynes** [comment]
If you can change the RXM_RAWX class to match I think that’s it. Thanks!

**Comment by valeriob** [comment]
Oh i thought that messages had to match message ids names

**Comment by jefffhaynes** [comment]
Nah, they probably should but I decided renaming all the indicators from what’s in the spec would be confusing. Since the classes are part of the public API I tried to make them more human readable.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by valeriob** [comment]
Done !
Do you mind to create a license for the project ? Maybe a permissive one, MIT or Apache ?

**Comment by jefffhaynes** [comment]
Oh yeah didn’t realize it didn’t have MIT specified. I’ll fix that.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by jefffhaynes** [comment]
Ok so I’m also noticing you’re using a lot of SerializeAs attributes vs simply using the matching types.  Is there a reason to use ints instead of byte, ushort, etc?  I think you can get rid of pretty much every SerializeAs attribute if you just use the right sized type.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by valeriob** [comment]
I was confused by the naming, i do not know how to translate some of those 
Int1 vs UInt1 are those byte ?

**Comment by valeriob** [comment]
what about now ? 😄

**Comment by jefffhaynes** [comment]
I’m not near my stuff so I can’t test it. Do you think it’s working?

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by valeriob** [comment]
Yep as soon as you publish a nuget package i'll use it in my project

**Comment by jefffhaynes** [comment]
Well the idea is to test it before I publish it :)

If you can’t I’ll do it this weekend

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by valeriob** [comment]
I've tested it, what i'm checking this days is verify that data is correct 😄

**Comment by jefffhaynes** [comment]
Ok. I’ll publish it later today. Thanks

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by jefffhaynes** [comment]
Pushed as part of ublox.Core 0.2.  Thanks.

**Pull request merged**
